export * from './pupil-add-dialog/pupil-add-dialog.component';
export * from './pupil-edit-dialog/pupil-edit-dialog.component';
export * from './pupils-list/pupils-list.component';
export * from './tutor-add-dialog/tutor-add-dialog.component';
export * from './tutor-edit-dialog/tutor-edit-dialog.component';
export * from './tutors-list/tutors-list.component';
export * from './user-add-dialog/user-add-dialog.component';
export * from './user-edit-dialog/user-edit-dialog.component';
export * from './users-list/users-list.component';
