export * from './pupils/pupil-add-dialog/pupil-add-dialog.component';
export * from './pupils/pupil-edit-dialog/pupil-edit-dialog.component';
export * from './pupils/pupils-list/pupils-list.component';
export * from './tutors/tutor-add-dialog/tutor-add-dialog.component';
export * from './tutors/tutor-edit-dialog/tutor-edit-dialog.component';
export * from './tutors/tutors-list/tutors-list.component';
export * from './users/user-add-dialog/user-add-dialog.component';
export * from './users/user-edit-dialog/user-edit-dialog.component';
export * from './users/users-list/users-list.component';
